### ISSUE TITLE
1.0.0-rc.18 win10环境编译失败

### ISSUE THREAD

**Issue by qqnp1100** [netease-kit/NIM-Flutter-SDK#1]
flutter 2.5.3
cmake 3.18.0-rc2

`Launching lib\main.dart on Windows in debug mode...
[downloadSDK]: sdk existing.
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(108,37): error C2220: 以下警告被视为错误 [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(108,37): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(108,48): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(121,18): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::write': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(148,37): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(148,48): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(160,18): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::write': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(325,37): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(325,48): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(329,22): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::write': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(346,37): warning C4996: 'nim_cpp_wrapper_util::Json::Reader': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(346,44): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::Reader': Use CharReader and CharReaderBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(347,19): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(369,37): warning C4996: 'nim_cpp_wrapper_util::Json::Reader': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(369,44): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::Reader': Use CharReader and CharReaderBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_chatroom_cpp_wrapper/helper/nim_chatroom_helper.h(370,19): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_talk_helper.h(171,37): warning C4996: 'nim_cpp_wrapper_util::Json::Reader': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_talk_helper.h(171,44): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::Reader': Use CharReader and CharReaderBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_talk_helper.h(173,25): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_talk_helper.h(176,24): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_talk_helper.h(185,23): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_talk_helper.h(298,37): warning C4996: 'nim_cpp_wrapper_util::Json::Reader': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_talk_helper.h(298,44): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::Reader': Use CharReader and CharReaderBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_talk_helper.h(299,19): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_msglog_helper.h(37,44): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_msglog_helper.h(37,56): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::write': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_msglog_helper.h(70,37): warning C4996: 'nim_cpp_wrapper_util::Json::Reader': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_msglog_helper.h(70,44): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::Reader': Use CharReader and CharReaderBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_msglog_helper.h(71,19): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_msg_helper.h(40,44): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_msg_helper.h(40,56): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::write': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_sysmsg_helper.h(82,37): warning C4996: 'nim_cpp_wrapper_util::Json::Reader': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_sysmsg_helper.h(82,44): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::Reader': Use CharReader and CharReaderBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_sysmsg_helper.h(83,20): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_subscribe_event_helper.h(87,37): warning C4996: 'nim_cpp_wrapper_util::Json::Reader': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_subscribe_event_helper.h(87,44): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::Reader': Use CharReader and CharReaderBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/helper/nim_subscribe_event_helper.h(88,19): warning C4996: 'nim_cpp_wrapper_util::Json::Reader::parse': Use CharReader and CharReaderBuilder instead. [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/api/nim_cpp_rts.h(68,37): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/api/nim_cpp_rts.h(68,48): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::FastWriter': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_cpp_wrapper/api/nim_cpp_rts.h(69,18): warning C4996: 'nim_cpp_wrapper_util::Json::FastWriter::write': Use StreamWriterBuilder instead [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_wrapper_util/nim_sdk_util.h(75,13): warning C4505: "nim::nim_print_unfound_func_name": 已删除具有内部链接的未引用函数 [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
F:\flutterEx\aitool\windows\flutter\ephemeral\.plugin_symlinks\nim_core_windows\nim_sdk\wrapper\nim_wrapper_util/nim_sdk_util.h(79,13): warning C4505: "nim::unfound_function_holder": 已删除具有内部链接的未引用函数 [F:\flutterEx\aitool\build\windows\plugins\nim_core_windows\nim_core_windows_plugin.vcxproj]
Exception: Build process failed.
Exited (sigterm)
`

**Comment by xiaoge136** [comment]
error C2220: 以下警告被视为错误
flutter 创建的APP时生成的CMakeLists.txt，对VS的警告级别设置原因，在CMakeLists.txt 找到下面类似这个的配置，加上/WX-
target_compile_options(${TARGET} PRIVATE /W4 /WX- /wd"4100")

**Comment by qqnp1100** [comment]
> error C2220: 以下警告被视为错误 flutter 创建的APP时生成的CMakeLists.txt，对VS的警告级别设置原因，在CMakeLists.txt 找到下面类似这个的配置，加上/WX- target_compile_options(${TARGET} PRIVATE /W4 /WX- /wd"4100")

`windows\CMakeLists.txt` 中有这个配置
```
function(APPLY_STANDARD_SETTINGS TARGET)
  target_compile_features(${TARGET} PUBLIC cxx_std_17)
  target_compile_options(${TARGET} PRIVATE /W4 /WX /wd"4100")
  target_compile_options(${TARGET} PRIVATE /EHsc)
  target_compile_definitions(${TARGET} PRIVATE "_HAS_EXCEPTIONS=0")
  target_compile_definitions(${TARGET} PRIVATE "$<$<CONFIG:Debug>:_DEBUG>")
endfunction()
```
`windows\flutter\CMakeLists.txt`中添加这段配置报错
```
CMake Error at flutter/CMakeLists.txt:116 (target_compile_options):
  Cannot specify compile options for target "PRIVATE" which is not built by
  this project.
```
