### ISSUE TITLE
nimi_core ^1.0.* NimCore.instance.messageService.querySessionList 获取最近会话列表数据，每条会话数据的extension是null

### ISSUE THREAD

**Issue by huzhiqin** [netease-kit/NIM-Flutter-SDK#13]
Flutter 3.0.2
nimi_core ^1.0.*以上版本
运行设备：iOS 、Android

NimCore.instance.messageService.querySessionList 拿到的 extension = null 

<img width="420" alt="image" src="https://user-images.githubusercontent.com/12080036/185561644-420e93ad-9173-4d2d-a66a-4f5f672c9e15.png">

只有通过拿这个session的session.id 再去调用 【NimCore.instance.messageService.queryLastMessage(session.sessionId, NIMSessionType.p2p】才能拿到remoteExtension

![image](https://user-images.githubusercontent.com/12080036/185562542-3dcedfc7-e46b-4e95-ae33-a2eef821a45f.png)

**Comment by netease-george** [comment]
Session 和 Message 是两个概念，Message中的 extension 不会出现在 Session中
