### ISSUE TITLE
nim_core 1.0.0-rc.33 初始化不返回结果

### ISSUE THREAD

**Issue by 12366** [netease-kit/NIM-Flutter-SDK#4]
生产环境
NimCore.instance.initialize(options)
    .then((result){
        if (result.isSuccess) {
            /// 初始化成功
        } else {
            /// 初始化失败
        }
    });
初始化不返回结果
I/flutter (15018): ALogService init with path: /data/user/0/com.chs.flutterapp/cache/nim/extra_log/NIMFlutter/, success: true
I/flutter (15018): ALog init result: true
result没有返回结果

登录结果也返回异常
I/flutter (15018): login result: NIMResult{code: -1, data: null, errorDetails: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference}

开发环境
Flutter 2.10.0,
Android 端开发：
Android Studio Bumblebee | 2021.1.1.21 Patch 1 for Windows 64-bit
Android SDK version 31.0.0)

开发调试模式没有上述问题，只有在生产真机运行环境或生产编译打包真机运行环境出现上述问题

**Comment by netease-george** [comment]
应该是混淆问题，请参考https://doc.yunxin.163.com/messaging/docs/Dg5NjI4MDg?platform=flutter
