### ISSUE TITLE
flutter3.0.1,android targetsdk31,nim_core-1.0.0-rc.53,编译报错

### ISSUE THREAD

**Issue by cgh89** [netease-kit/NIM-Flutter-SDK#9]
e: /Users/watson/Documents/Dev/SDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/nim_core-1.0.0-rc.53/android/src/main/kotlin/com/netease/nimflutter/MethodCallHandlerImpl.kt: (25, 43): Type mismatch: inferred type is Map<String, *>? but Map<String, *> was expected
e: /Users/watson/Documents/Dev/SDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/nim_core-1.0.0-rc.53/android/src/main/kotlin/com/netease/nimflutter/SafeResult.kt: (15, 1): Class 'SafeResult' is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /Users/watson/Documents/Dev/SDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/nim_core-1.0.0-rc.53/android/src/main/kotlin/com/netease/nimflutter/SafeResult.kt: (23, 5): 'error' overrides nothing
e: /Users/watson/Documents/Dev/SDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/nim_core-1.0.0-rc.53/android/src/main/kotlin/com/netease/nimflutter/SafeResult.kt: (24, 46): Type mismatch: inferred type is String? but String was expected
e: /Users/watson/Documents/Dev/SDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/nim_core-1.0.0-rc.53/android/src/main/kotlin/com/netease/nimflutter/SafeResult.kt: (46, 1): Class 'MethodChannelSuspendResult' is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /Users/watson/Documents/Dev/SDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/nim_core-1.0.0-rc.53/android/src/main/kotlin/com/netease/nimflutter/SafeResult.kt: (54, 5): 'error' overrides nothing

**Comment by ivesjob2015** [comment]
一样的错 解决了没？

**Comment by AnyMarvel** [comment]
一样的错误，sdk语法错误，这个问题解决了么

**Comment by netease-george** [comment]
正式版本已经适配 flutter 3.0 ，请使用正式版本^1.0.8
